# -*- coding: utf-8 -*-
"""aula1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r_1xRDOuzznLh1oL2LhmQbOhCdV3kx50
"""

# Projeto Alura

import pandas as pd

df = pd.read_csv("/content/Gapminder.csv", error_bad_lines = False, sep=";")

df.head(10)

df.tail()

df.columns=["País","Continente","Ano","Expectativa de Vida","População","PIB Percapta"]

df.head(10)

df.shape

df.dtypes

df.describe()

df["Continente"].unique()

oceania = df.loc[df["Continente"] == "Oceania"]

oceania.head()

df.groupby("Continente")["País"].nunique()

df.groupby("Ano")["Expectativa de Vida"].mean()

df.mean()

df.sum()

